### PR TITLE
feat: update implementation of importAccountsInSecureContext on Sender Wallet

### PR DESCRIPTION
**Pull request by chachaxw**
**Description**

This PR contains initial implementation for adding importAccountsInSecureContext interface for Sender Wallet. [WEP-212](https://pagodaplatform.atlassian.net/browse/WEP-212)

**Checklist:**

 - [x] I have performed a self-review of my own code
 - [x] I have commented my code, particularly in hard-to-understand areas
 - [x] I have made corresponding changes to the documentation
 - [x] My changes generate no new warnings

**Type of change.**

 - [ ] FIX - a PR of this type patches a bug.
 - [x] FEATURE - a PR of this type introduces a new feature.
 - [ ] BUILD - a PR of this type introduces build changes.
 - [ ] CI - a PR of this type introduces CI changes.
 - [ ] DOCS - a PR of this type introduces DOCS improvement.
 - [ ] STYLE - a PR of this type introduces style changes.
 - [ ] REFACTOR - a PR of this type introduces refactoring.
 - [ ] PERFORMANCE - a PR of this type introduces performance changes.
 - [ ] TEST - a PR of this type adds more tests.
 - [ ] CHORE - a PR introduces other changes than the specified above.

[WEP-212]: https://pagodaplatform.atlassian.net/browse/WEP-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by kujtimprenkuSQA** [comment]
Hi, @chachaxw Thank you for submitting this PR.

While testing it out in different networks we noticed few issues:

Even though the accounts have enough balance when the import process finishes Sender shows this message:

step-4


If you try to sign-in to a dApp with the newly imported account it shows this UI even though the account exists and has enough balance:
image

Even though sometimes for some accounts it does not show the message "Account is not initialized" while trying to sign-in to a dApp we get this error:

image

Also, can you please remove that redirect to the Sender Twitter page when the import accounts process finishes?

**Comment by chachaxw** [comment]
> Hi, @chachaxw Thank you for submitting this PR.
> 
> While testing it out in different networks we noticed few issues:
> 
> Even though the accounts have enough balance when the import process finishes Sender shows this message:
> 
> step-4
> 
> If you try to sign-in to a dApp with the newly imported account it shows this UI even though the account exists and has enough balance: image
> 
> Even though sometimes for some accounts it does not show the message "Account is not initialized" while trying to sign-in to a dApp we get this error:
> 
> image
> 
> Also, can you please remove that redirect to the Sender Twitter page when the import accounts process finishes?

It seems it's sender wallet extension issues. The near Testnet RPC node not working any more, we have changed Testnet RPC Node on version v2.0.8, and we will release this version on these days. Please notice this, thanks.

**Comment by kujtimprenkuSQA** [comment]
Thank you for taking a look at this and informing us about the progress.

**Comment by chachaxw** [comment]
@kujtimprenkuSQA If you want to test this PR quickly, I think I can send you a sender wallet test version, and you can test it by that one.

**Comment by kujtimprenkuSQA** [comment]
> @kujtimprenkuSQA If you want to test this PR quickly, I think I can send you a sender wallet test version, and you can test it by that one.

Sure, we can do that. But the PR will be merged only after it's live on production.

**Comment by kujtimprenkuSQA** [comment]
> > > @kujtimprenkuSQA If you want to test this PR quickly, I think I can send you a sender wallet test version, and you can test it by that one.
> > 
> > 
> > Sure, we can do that. But the PR will be merged only after it's live on production.
> 
> So how can I send you sender wallet test version?

Can you send it privately on Telegram?

**Comment by kujtimprenkuSQA** [comment]
After testing the latest "test" version of Sender everything seems to be working fine importing accounts in `mainnet` and `testnet`.

The PR looks good to me and it will be merged once Sender publishes a new version with the fixes.

**Pull request merged**
