### PR TITLE
feat: add Xoth mobile wallet

### PR DESCRIPTION
**Pull request by chezhe**
Description
Xoth Wallet is mobile wallet that support NEAR protocol & Octopus Network. You can read more information in [here](https://xoth.app/).

Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

 My changes generate no new warnings

Type of change.
- [ ] FIX - a PR of this type patches a bug.
- [x] FEATURE - a PR of this type introduces a new feature.
- [ ]  BUILD - a PR of this type introduces build changes.
- [ ]  CI - a PR of this type introduces CI changes.
- [ ]  DOCS - a PR of this type introduces DOCS improvement.
- [ ]  STYLE - a PR of this type introduces style changes.
- [ ]  REFACTOR - a PR of this type introduces refactoring.
- [ ]  PERFORMANCE - a PR of this type introduces performance changes.
- [ ]  TEST - a PR of this type adds more tests.
- [ ]  CHORE - a PR introduces other changes than the specified above.

### CODE REVIEW

**Comment by kujtimprenkuSQA** [comment]
Hey, @chezhe thank you for submitting this PR.

I had a look at the PR and to test the Xoth Wallet I forked the project from you and deployed it here temporarily:
https://kujtimprenkusqa.github.io/wallet-selector/

While I am on a mobile device the `Xoth Wallet` option shows in the modal but when I click the option it redirects to a website that is not working: https://wallet.testnet.xoth.app

Looking at the source code of this package it looks like a more or less "copy" of the MyNearWallet (I am not saying there's anything wrong with that):
https://github.com/NonceLabs/wallet-selector/tree/feat/xoth/packages/xoth

It's just that I am a bit confused and these are two questions I would like to clarify:

**Does `Xoth Wallet` support NEAR without WalletConnect?**
**Is there a way to communicate with the wallet through the option which is shown in the modal?**

Your wallet works fine with the `WalletConnect` option we have 👍 

One suggestion would be that in `Transactions` with `deposit`/`donation ` it would be nice to show the amount of the `deposit` in the UI of the wallet before confirming or rejecting.

**Comment by chezhe** [comment]
> 

Yes, it copied from MyNearWallet. In fact, in Xoth Wallet, if you select MyNearWallet or NearWallet, it works too. But most of users won't know how to select a wallet from the selector, so I submit this pr to add Xoth wallet selector on the list, so that users know what to select on Xoth Wallet.
This url https://wallet.testnet.xoth.app/ isn't accessible which does not matter, Xoth Wallet will recognize if the dApp wants to connect or sign transactions.

**Comment by chezhe** [comment]
Can we add a note on the WalletConnect modal to let users know they can connect with Xoth wallet?

**Comment by chezhe** [comment]
> One suggestion would be that in Transactions with deposit/donation it would be nice to show the amount of the deposit in the UI of the wallet before confirming or rejecting.

Nice suggestion. We will update on our next update.

**Comment by AmmarHumackicSQA** [comment]
> Can we add a note on the WalletConnect modal to let users know they can connect with Xoth wallet?

Hi @chezhe , we are working on implementing the QR code (WalletConnect option for now) inside the Wallet Selector modal while following the already set design for it. Maybe in the future, we can add some info, as you suggested. Thanks!

**Comment by chezhe** [comment]
You can test by this way.
Open a your test DApp in Xoth Wallet explorer, click "login" button, select Nearwallet or MyNearWallet, it will work well(including sign transaction), which means Xoth wallet support users login and sign with Nearwallet and MyNearWallet.

**Comment by chezhe** [comment]
> You can test by this way. Open a your test DApp in Xoth Wallet explorer, click "login" button, select Nearwallet or MyNearWallet, it will work well(including sign transaction), which means Xoth wallet support users login and sign with Nearwallet and MyNearWallet.

However, users may not know they can login and sign by selecting NearWallet or MyNearWallet in Xoth Wallet dApp browser, so I think a better way to add Xoth wallet to wallet-selector, so that event new users who don't know NEAR much can use it without questions.
 
The redirect to https://wallet.testnet.xoth.app/ just let Xoth wallet know the attempt to login or sign transactions.

**Comment by chezhe** [comment]
@kujtimprenkuSQA I think you misunderstood this PR. This PR has nothing to do with WalletConnect, to login and sign desktop dApp, users can connect WC with Xoth Wallet.
This PR is for the users who open dApps on Xoth Wallet, they open a dApp, and click the wallet selector, then select Xoth Wallet icon to login.
This PR empower users interact with dApps on mobile and desktop with Xoth Wallet.

**Comment by chezhe** [comment]
@kujtimprenkuSQA Do you still have questions?

**Comment by kujtimprenkuSQA** [comment]
>However, users may not know they can login and sign by selecting NearWallet or MyNearWallet in Xoth Wallet dApp browser, so I think a better way to add Xoth wallet to wallet-selector, so that event new users who don't know NEAR much can use it without questions.

If the goal of this PR is to let the users know that `Xoth Wallet` has an **in-built browser** where there are different dApps listed that support NEAR Wallet Selector then I am afraid this PR can not be merged as it is.

When a wallet is added to the options in the Modal these are the expectations and  requirements:
- Clicking the option initiates the `signIn` process.
- When signed in you can call `signAndSendTransaction(s)` with different action types (which the wallet supports).
- You can successfully call any other `wallet` method like (`verifyOwner, getAccounts etc.).

So the added wallet option must support all the API's described here in the docs:
https://github.com/near/wallet-selector/blob/main/packages/core/docs/api/wallet.md

At the current state of this PR none of the above steps are implemented.

>The redirect to https://wallet.testnet.xoth.app/ just let Xoth wallet know the attempt to login or sign transactions.

We can not redirect users to a non-working website.

---

What is the purpose of this commit: [`use injected window.xoth`](https://github.com/near/wallet-selector/pull/478/commits/b2d19d1105d7ecf3dec2b5b2be59d5211d5353ce)?
- How are you injecting the `xoth` property in the window object?
- How are you interacting with `window.xoth`?
- At the moment `window.xoth` always returns `undefined` which means the Xoth Wallet option will never show because of the if check in setup function.

**Comment by chezhe** [comment]
`window.xoth` will be injected at Xoth Wallet v1.1.8 which is next version (still in review of stores).
Xoth Wallet works logic just like NearWallet, when the page redirects https://wallet.testnet.xoth.app/login, Xoth Wallet will return public key; https://wallet.testnet.xoth.app/sign, Xoth will sign the transaction in the search params.

**Comment by kujtimprenkuSQA** [comment]
I see we will wait until it's published in the stores. 
In the meantime can you change the base branch of this PR to `dev` because we do not merge these PR's directly to `main` branch?
Have a look at the docs for more details:
https://github.com/near/wallet-selector/blob/main/CONTRIBUTING.md#branching

After the app has been approved in the stores let us know and if the call is still needed I will contact you for sure then.

**Comment by chezhe** [comment]
OK。
Android version is already published.

**Comment by chezhe** [comment]
iOS v1.1.8 published too.

**Comment by kujtimprenkuSQA** [comment]
Hey, @chezhe thank you for the update.

At the moment the Testnet RPC is having a `Partial outage` once it's back on I will test out the new version.

**Comment by chezhe** [comment]
We're rebranding our wallet, will submit a new PR.

**Pull request closed without merging**
