### PR TITLE
add support signMessage in nightly wallet

### PR DESCRIPTION
**Pull request by Pawel-Szydlo**
# Description

Please include a summary of the wallet and how users can install it. Be sure to take a look at our guide on [Custom Wallets](https://github.com/near/wallet-selector/blob/main/packages/core/docs/guides/custom-wallets.md) to understand core concepts when integrating with Wallet Selector.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by erditkurteshiSQA** [comment]
Hi @Pawel-Szydlo ,
Thank you for raising this PR.

Can you please change the branch from `main` to `dev`?

We are getting an error message while testing signMessage. 
The message is shown after we approve the `Signature Request`.

Please take a look at the image below for the information.

image

**Comment by Pawel-Szydlo** [comment]
> Hi @Pawel-Szydlo , Thank you for raising this PR.
> 
> Can you please change the branch from `main` to `dev`?
> 
> We are getting an error message while testing signMessage. The message is shown after we approve the `Signature Request`.
> 
> Please take a look at the image below for the information.
> 
> image

Hi, a new version of the nightly extension came out this morning, 1.0.4 to be exact. This version has support for signMessage, if you could test it again.
Sorry for the confusion.

**Comment by erditkurteshiSQA** [comment]
Hi @Pawel-Szydlo

While testing out the signMessage we have some other requirements for the implementation.

The UI that shows `Signature Request` for the user to approve the signMessage, should contain
more information about what this action/function does.

I will attach a similar UI ( Meteor Wallet ) below to give you an example:
image


Also, the dApp developers should be able to call signMessage even if they are not connected or signedIn.

**Comment by Pawel-Szydlo** [comment]
@erditkurteshiSQA 
- What requirements do you have for the implementation of signMessage?

Nightly has its own simple, clear user interface. It is additionally clear which site the wallet is linked to.

image
image

> Also, the dApp developers should be able to call signMessage even if they are not connected or signedIn.
please explain how this would work?

**Please explain how this would work?**

Because if the user hasn't selected the nightly extension from the wallet list, how does the dApp developer know that they can call the signMessage method from the nightly version? So, nightly users first have to connect to the page in question, and then the methods **signAndSendTransaction**, **signMessage**, etc., can be called

**Comment by erditkurteshiSQA** [comment]
@Pawel-Szydlo ,

The idea of `signMessage` is for dApps to be sign messages without having to create Limited Access Keys (function-call access-key).
In a dApp you can programmatically call the nightly signMessage without using the modal:

```ts
(async () => {
  const wallet = await selector.wallet("nightly");
  const message = "test message for verification";
  let nonceArray: Uint8Array = new Uint8Array(32);
  nonceArray = crypto.getRandomValues(nonceArray);
  const nonce = Buffer.from(nonceArray);
  const recipient = "myapp.com";

  await wallet.signMessage({ message, recipient, nonce });
})();
```

Also for more information, I will attach the link below:
https://github.com/near/NEPs/blob/master/neps/nep-0413.md

**Comment by Pawel-Szydlo** [comment]
@erditkurteshiSQA 
I understand.

Nightly does not use limited access keys, so users do not need NEAR to sign the message.

The connection to the page is for security purposes, preventing unwanted pages from sending requests to the Nightly wallet. Therefore, Nightly users first connect to the page (browser tab), and then methods can be called from the Nightly interface.

**Comment by erditkurteshiSQA** [comment]
@Pawel-Szydlo 

Can you first check if the wallet is connected then sign the message: 

```
if (!_state.wallet.connected) {
 await _state.wallet.connect();
} 
```

and then call signMessage method.

**Comment by Pawel-Szydlo** [comment]
@erditkurteshiSQA 
good idea, changes added to pr.

**Review by erditkurteshiSQA — APPROVED** [review]

**Pull request merged**
