### PR TITLE
feat: add the new toggle functionality

### PR DESCRIPTION
**Pull request by pivanov**
# Description

Implement Previous selected Wallet
[Video](https://u.pcloud.link/publink/show?code=XZuiPP0ZUmtEGBM7akY67dddQ40P9zzBXdtV )

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Type of change.

- [ ] FIX - a PR of this type patches a bug.
- [x] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [ ] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [ ] CHORE - a PR introduces other changes than the specified above.

### CODE REVIEW

**Review by gtsonevv — APPROVED** [review]

**Comment by trechriron** [comment]
The music over the video was a nice touch!

**Review by trechriron — CHANGES_REQUESTED** [review]
Please provide more spacing between the Recent and other wallets. Otherwise, this is amazing!

**Comment by pivanov** [comment]
> Please provide more spacing between the Recent and other wallets. Otherwise, this is amazing!

Hey @trechriron 

Here is the improved version :)
[Video](https://u.pcloud.link/publink/show?code=XZDutC0ZRpnkQPfGbfHlVCG6kmVGdHcwCC1X)

What do you think?

**Review by gtsonevv — APPROVED** [review]

**Review by gtsonevv — APPROVED** [review]

**Review by pivanov — COMMENTED** [review]
Fixed

**Pull request merged**
