### PR TITLE
v8.9.6 Release (dev -> main)

### PR DESCRIPTION
**Pull request by trechriron**
# Description

Merge **https://github.com/near/wallet-selector/pull/1085** & **https://github.com/near/wallet-selector/pull/1077**

# Checklist:

- [NA] I have performed a self-review of my own code
- [NA] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# Type of change.

- [ ] FIX - a PR of this type patches a bug.
- [X] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [ ] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [ ] CHORE - a PR introduces other changes than the specified above.

### CODE REVIEW

**Comment by hcho112** [comment]
Please refer to this PR for convention to release a new package:
https://github.com/near/wallet-selector/pull/1076
1. Check its title, content
2. Previously it is requested to bump ALL the package versions together. (Bumping up version is essential to get the packages automatically deployed to NPM)

**Comment by trechriron** [comment]
Changed title.

**Comment by trechriron** [comment]
Need versions in json updated first. Will create new PR when ready.

**Comment by trechriron** [comment]
Will use this PR after fixing dev version bump.

**Review by hcho112 — DISMISSED** [review]
LGTM

**Review by andy-haynes — APPROVED** [review]

**Pull request merged**
