### PR TITLE
feat: add implementation of importAccountsInSecureContext on Nightly Wallet

### PR DESCRIPTION
**Pull request by Pawel-Szydlo**
# Description

This PR contains implementation for adding importAccountsInSecureContext interface on Nightly Wallet.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Type of change.

- [ ] FIX - a PR of this type patches a bug.
- [x] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [ ] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [ ] CHORE - a PR introduces other changes than the specified above.

### CODE REVIEW

**Comment by amirsaran3** [comment]
Hey @Pawel-Szydlo How can I test this functionality. I can't find any button to import accounts in Nightly Wallet.

**Comment by Pawel-Szydlo** [comment]
hey, I tested on your "examples". 
I think you can test it there.

**Comment by hcho112** [comment]
@Pawel-Szydlo 
I have pull down nightly repo main and ran the local env with test account. Unfortunately  I'm seeing this:
image

And the view from Nightly Wallet is idle. Can you revisit this?
Also, I would advise to reference the latest wallet-selector, v7.6.1

Cheers

**Comment by Pawel-Szydlo** [comment]
hey, could I have { accountId: "test.testnet", privateKey: "ed25519:..."} on which you tested? I would be able to reproduce the error

**Comment by hcho112** [comment]
with latest change on chrome extension, I have confirm that this PR is working as expected on testnet 👍 
(FYI, to visualize account(s) after import, make sure that network is set to testnet on chrome extension app)

**Review by hcho112 — APPROVED** [review]
LGTM

**Pull request merged**
