### PR TITLE
docs: remove duplicate `setupNearSnap`

### PR DESCRIPTION
**Pull request by zavodil**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Type of change.

- [ ] FIX - a PR of this type patches a bug.
- [ ] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [x] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [ ] CHORE - a PR introduces other changes than the specified above.

### CODE REVIEW

**Comment by trechriron** [comment]
1. You did not select a template for the initial comment. This is a requirement! You'll need to use the template provided, provide clear change details, and make selections in the checkboxes.
2. You always make your initial PR against the DEV branch.

Please resubmit this PR correctly. Thanks.

**Review by trechriron — DISMISSED** [review]
Please see comments.

**Comment by trechriron** [comment]
@zavodil  - did you see the requested changes?

**Comment by zavodil** [comment]
I fixed a README.md typo using github web version. Do with it what you deem necessary.

**Review by pivanov — APPROVED** [review]

**Review by pivanov — APPROVED** [review]

**Pull request merged**
