### PR TITLE
fix: add Korean to the LanguageSelector

### PR DESCRIPTION
**Pull request by flmel**
# Description

While adding the Bulgarian translation I noticed Korean is missing from the LanguageSelectorComponent Maybe a guide of few lines on the README for translation contributors will help

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Type of change.

- [x] FIX - a PR of this type patches a bug.
- [ ] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [ ] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [ ] CHORE - a PR introduces other changes than the specified above.

### CODE REVIEW

**Comment by kujtimprenkuSQA** [comment]
@flmel thank you for submitting this PR.

Currently, language is detected only from the browser's language it's mentioned here https://github.com/near/wallet-selector/blob/dev/packages/core/docs/guides/multilanguage-support.md, that's why we don't mention updating the UI components in the docs. Switching language from `modal-ui` is not supported yet.

**Review by kujtimprenkuSQA — APPROVED** [review]

**Comment by flmel** [comment]
Oh thanks, somehow I did miss this README

**Comment by DamirSQA** [comment]
Hi @flmel new section "Export Account" is added recently, so it would be great if there's translation [for it](https://github.com/near/wallet-selector/blob/main/packages/core/src/lib/locale/en.json#L58) as well. Would you be able provide it? Thanks.

**Comment by flmel** [comment]
> Sure

**Comment by flmel** [comment]
@DamirSQA  Sure, will get to it.

**Pull request merged**
